import React from 'react'

const Training = () => {
  return <section>
    <h1>Training and Experience</h1>
    <ul>
      <li>Working with Survivors of Sexual Abuse</li>
      <li>Bereavement in a secure setting</li>
      <li>Relationship First Aid (mediation)</li>
      <li>Sleep and Insomnia</li>
      <li>Young Minds (adolescent mental health) – Qualified trainer</li>
      <li>Treating Problem Behaviour - Trauma Reconciliation Intervention</li>
      <li>Trauma and Attachment</li>
      <li>Safe Talk Suicide alertness</li>
      <li>Life Story work</li>
      <li>Motivational Interviewing</li>
      <li>Therapeutic Crises Intervention</li>
      <li>Adult Resilience</li>
      <li>Risk Assessment training for Sexual behaviour</li>
      <li>Working with resistant and non- compliant families</li>
      <li>Family Therapy</li>
      <li>Child Protection - experienced practitioner</li>
      <li>Zero Tolerance (Sexual Exploitation)</li>
    </ul>
  </section>
}

export default Training